name: Check tarball build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install platform dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y build-essential python3-dev python3-pip libpq-dev libffi-dev libssl-dev libkrb5-dev zlib1g-dev

      - name: Install Python dependencies
        run: |
          sudo pip install --upgrade pip
          sudo pip install -r requirements.txt
          sudo pip install "pyOpenSSL>=23.*" sphinx sphinxcontrib-youtube

      - name: Check the tarball build
        run: make src

      - name: Archive source tarball
        uses: actions/upload-artifact@v3
        with:
          name: pgadmin4-tarball-build-output
          path: dist/*
