name: Check Javascript style

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install platform dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y nodejs npm

      - name: Install Node dependencies
        run: sudo npm install --global yarn

      - name: Install Node modules
        run: |
          export CPPFLAGS="-DPNG_ARM_NEON_OPT=0"
          cd web
          yarn install

      - name: Run the linter
        run: |
          cd web
          yarn run linter
