name: Check Python style

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install platform dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y python3-pip

      - name: Install Python dependencies
        run: |
          sudo pip install --upgrade pip
          sudo pip install pycodestyle

      - name: Check the documentation
        run: pycodestyle --config=.pycodestyle docs/

      - name: Check the packaging
        run: pycodestyle --config=.pycodestyle pkg/

      - name: Check the application
        run: pycodestyle --config=.pycodestyle web/

      - name: Check the tools
        run: pycodestyle --config=.pycodestyle tools/
